---
title: "Euro 2021 Age Country Stats"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    css: 04_css.css
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)

# Core
library(tidyverse)

# Visualization
library(plotly)
library(DT)
```

```{css}
.bootstrap-switch, .bootstrap-switch-handle-on,
.bootstrap-switch, .bootstrap-switch-handle-off,
.bootstrap-switch, .bootstrap-switch-label {
display: inline-block;
vertical-align: baseline;
}
```

```{r}
# Data
data <- readRDS("00_Data/euro_2021_data.rds")

source("functions.R")
```

Sidebar {.sidebar}
-----------------------------------------------------------------------
```{r}
# Inputs

# # Country Profile
# output$country_name <- renderPrint(input$country)
# textOutput(outputId = "country_name")


# 
# br()
br()
hr()

# All vs Country Button
h4("Country Mode")
switchInput(inputId     = "country_mode", 
            handleWidth = 100, 
            labelWidth  = 100, 
            inline      = TRUE, 
            width       = "200px",
            value       = FALSE,
            onLabel     = "On",
            offLabel    = "Off" 
            )

hr()

# # Action Button Apply
# actionButton(inputId = "apply", label = "Apply", icon = icon("play"))
# 
# br()
# hr()

# Country Selector
pickerInput(
   inputId = "country",
   label   = h4("Country"),
   choices = unique(data$country),
   options = list(size = 5)
)

hr()
br()

# Action Button Reset
actionButton(inputId = "reset", label   = "Reset", icon    = icon("sync"))




# # Apply Button Link
# eventReactive(
#     eventExpr = input$apply,
#     valueExpr = input$country_mode
# )


# Reset Button Link
observeEvent(
    eventExpr = input$reset, 
    handlerExpr = {
        
        # Reset Country Selector
        updatePickerInput(
            session  = session,
            inputId  = "country",
            selected = unique(data$country))
        
        # Country Mode
        updateSwitchInput(
            session  = session,
            inputId  = "country_mode",
            value    = FALSE
            )
        }
    )

```


Column {data-height=170}
-----------------------------------------------------------------------

### Country Info

```{r}
# Data Filter
data_tbl <- reactive({
    
    if (input$country_mode) {
        data <- data %>% 
            filter(country == input$country)
    } else {
        data <- data
    }
    return(data)
})

output$country_info_box <- reactive({

    # Selected Country Output
    country_info <- data_tbl() %>% func_country_profile()
    player_info  <- data_tbl() %>% func_player_profile()
    selected_country_output <- str_glue("{country_info}
                                         {player_info}")
    # All Country Output (Default)
    all_country_output <- data_tbl() %>% func_default_message()

    if (input$country_mode) {
        output <- selected_country_output
    } else {
        output <- all_country_output
    }
    return(output)

})

verbatimTextOutput(outputId = "country_info_box") 


```


Column {data-height=700}
-----------------------------------------------------------------------

### Age Distribution

```{r}
age_distribution_data <-  reactive({

    if (input$country_mode) {
        data %>% filter(country == input$country)
    } else {
         data
    }
})



# output$plotly_1 <- renderPlotly(expr = {
#     
#     data_tbl() %>% func_plot_age_distribution()
# })
# 
# plotlyOutput(outputId = "plotly_1")

renderPlot({

    age_distribution_data() %>% func_plot_age_distribution()
})

```



